
services:
  postgres:
    image: postgres:15
    container_name: skidor_postgres
    restart: always
    environment:
      POSTGRES_USER: skidor_user
      POSTGRES_PASSWORD: skidor_pass
      POSTGRES_DB: skidor_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
# fixa vart volymerna pekar på
volumes:
  postgres_data:


# Kommandon för att hantera containern:

    # Starta containern: docker-compose -f src/docker/docker-compose.yml up -d
    # Stoppa containern (men data behålls): docker-compose -f src/docker/docker-compose.yml down
    # Ta bort container och data: docker-compose -f src/docker/docker-compose.yml down -v
